github: pranavmappoli
patreon: pranavmappoli
open_collective: pranavmappoli
ko_fi: pranavmappoli
tidelift: npm/package-name  # Replace "package-name" with the actual Tidelift package name you want to reference
community_bridge: project-name  # Replace "project-name" with your actual Community Bridge project name
liberapay: pranavmappoli
issuehunt: pranavmappoli
otechie: pranavmappoli
custom: ['https://pranavmappoli.github.io', 'https://www.linkedin.com/in/pranavmapppoli',] 
